/******************************************************************************
 * @file    main.c
 * @author  Bhumija Roy Yadiki
 * @brief   Application entry point for the BMA423 driver demonstration.
 *
 * This application initializes the complete software stack required to
 * acquire accelerometer data from the Bosch BMA423.
 *
 * Initialization Sequence
 * ---------------------------------------------------------------------------
 *      ESP32 Boot
 *           │
 *           ▼
 *     Initialize I2C Bus
 *           │
 *           ▼
 *   Initialize Power Subsystem
 *           │
 *           ▼
 *      Scan I2C Devices
 *           │
 *           ▼
 *     Configure BMA423 Sensor
 *           │
 *           ▼
 *  Initialize Interrupt Subsystem
 *           │
 *           ▼
 *      Driver Ready
 *
 * The initialization order is intentional. The interrupt subsystem is
 * enabled only after the sensor has been completely configured. This
 * prevents the ESP32 from servicing interrupts generated by an
 * uninitialized device.
 ******************************************************************************/

#include <stdio.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "i2c.h"
#include "power.h"
#include "bma423.h"
#include "bma423_isr.h"

/******************************************************************************
 * @brief Application entry point.
 *
 * Initializes all hardware and software components required by the
 * BMA423 driver. Initialization is performed sequentially so that each
 * subsystem is verified before the next depends on it.
 *
 * Startup Sequence
 * ----------------
 * 1. Initialize the shared I2C transport layer.
 * 2. Initialize the AXP202 power-management subsystem.
 * 3. Scan the I2C bus for connected peripherals.
 * 4. Configure the BMA423 sensor.
 * 5. Enable the interrupt handling subsystem.
 *
 * If any stage fails, startup is aborted immediately to prevent the
 * application from operating with partially initialized hardware.
 ******************************************************************************/
void app_main(void)
{
    /*
     * Initialize the shared I2C transport layer.
     *
     * This must complete successfully before any peripheral on the
     * shared I2C bus can be accessed.
     */
    if (i2c_init() != I2C_OK)
    {
        printf("[MAIN] Failed to initialize I2C subsystem\n");
        return;
    }

    /*
     * Initialize the power-management IC.
     *
     * The AXP202 powers multiple onboard peripherals, including the
     * BMA423. Communication with the sensor is not attempted until the
     * required power rails have been enabled.
     */
    if (power_init() != ESP_OK)
    {
        printf("[MAIN] Failed to initialize power subsystem\n");
        return;
    }

    /*
     * Enumerate all devices detected on the shared I2C bus.
     *
     * This serves as a diagnostic step during development and confirms
     * that expected peripherals are responding before driver
     * initialization begins.
     */
    i2c_scan();

    /*
     * Configure the BMA423.
     *
     * This performs the complete sensor initialization sequence,
     * including:
     *  - Soft reset
     *  - Chip-ID verification
     *  - Error register validation
     *  - Register configuration
     *  - Interrupt routing
     *  - Power configuration
     */
    printf("[MAIN] Initializing BMA423...\n");

    bma423_status_t status = bma423_init();

    if (status != BMA423_OK)
    {
        printf("[MAIN] BMA423 initialization failed (status = %d)\n",
               status);
        return;
    }

    /*
     * Enable the interrupt handling subsystem.
     *
     * Interrupt processing is deliberately initialized only after the
     * sensor has been fully configured. This prevents the ISR from
     * servicing interrupts before the device is ready to provide valid
     * accelerometer data.
     */
    printf("[MAIN] Initializing interrupt subsystem...\n");

    status = bma423_isr_init();

    if (status != BMA423_OK)
    {
        printf("[MAIN] Failed to initialize interrupt subsystem\n");
        return;
    }

    /*
     * System startup complete.
     *
     * From this point onward, accelerometer samples are acquired
     * automatically through the interrupt-driven processing pipeline.
     */
    printf("[MAIN] BMA423 driver initialized successfully.\n");
}